[project]
name = "pipeline-bacen"
version = "0.1.0"
description = ""
authors = [
    {name = "VinicinCanedo",email = "vinicanedo@hotmail.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.4,<3.0.0)",
    "streamlit (>=1.45.1,<2.0.0)"
]

[tool.poetry]
packages = [{include = "pipeline_bacen", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
